Stat svc
zg-devj/java-explore-with-me pull request #3
Opened 2023-06-29 08:19 UTC by zg-devj

2023-06-29 09:33 UTC, TomattmanYandex requested changes
Привет все хорошо, но паттерн под ip и название модуля очень смущают

2023-06-29 09:33 UTC, TomattmanYandex commented on stats-service/library/src/main/java/ru/practicum/statsservice/library/EndpointHitDto.java
> +package ru.practicum.statsservice.library;
не самое лучшее имя для подпакета
обычно обзывают все же как то ближе к функционалу
если что то общее для всех подпроектов то хорошее имя common

2023-06-29 11:05 UTC, zg-devj commented on stats-service/library/src/main/java/ru/practicum/statsservice/library/EndpointHitDto.java
> +    @Pattern(regexp = "(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)")
Убрал. Только для IPv4.

2023-06-29 11:34 UTC, zg-devj commented on stats-service/library/src/main/java/ru/practicum/statsservice/library/EndpointHitDto.java
> +package ru.practicum.statsservice.library;
Изменил, но фантазия у меня не очень.

2023-06-29 21:53 UTC, TomattmanYandex approved these changes
Принтяо, но к следующей сдаче измени название модуля

2023-06-29 21:53 UTC, TomattmanYandex commented on stats-service/statsdto/src/main/java/ru/practicum/statsservice/library/EndpointHitDto.java
> +package ru.practicum.statsservice.library;
назови лучше модуль common

2023-06-30 06:17 UTC, zg-devj commented on stats-service/statsdto/src/main/java/ru/practicum/statsservice/library/EndpointHitDto.java
> +package ru.practicum.statsservice.library;
Спасибо.

2023-06-30 06:35 UTC, merged