Feature location processing
zg-devj/java-explore-with-me pull request #5
Opened 2023-07-19 21:25 UTC by zg-devj

2023-07-20 12:01 UTC, TomattmanYandex requested changes
Есть моменты которые надо поправить

2023-07-20 13:03 UTC, zg-devj commented on main-service/src/main/java/ru/practicum/mainservice/event/criteria/EventSpecs.java
> +//    public static Specification<Event> isLoc(Double lat, Double lon, double radius) {
Исправил

2023-07-20 13:04 UTC, zg-devj commented on main-service/src/main/java/ru/practicum/mainservice/location/LocationEntity.java
> +    private long id;
Исправил

2023-07-20 13:12 UTC, zg-devj commented on main-service/src/main/java/ru/practicum/mainservice/location/LocationMapper.java
> +        Location coordinate = Location.builder()
Исправил

2023-07-20 13:24 UTC, zg-devj commented on main-service/src/main/java/ru/practicum/mainservice/location/LocationServiceImpl.java
> +    public List<LocationFullDto> adminFindLocations(List<LocationStatus> statuses, int from, int size) {
Я оставлю как есть. Буду придерживаться стиля именования методов принятом в начале проекта.
PS: yandex переводчик переводит "findLocationByAdmin" : поиск местоположения с помощью администратора. 
Не совсем соответствует методу.

2023-07-20 13:28 UTC, zg-devj commented on main-service/src/main/java/ru/practicum/mainservice/location/LocationServiceImpl.java
> +        return getLocationDto(newLocationDto, LocationStatus.PUBLISHED, null);
В методе getLocationDto. Не удачное название метода. Переименовал в : addLocation

2023-07-20 13:28 UTC, zg-devj commented on main-service/src/main/java/ru/practicum/mainservice/location/LocationServiceImpl.java
> +        return getLocationDto(newLocationDto, LocationStatus.PENDING, user);
Исправил, выше написал.

2023-07-20 13:29 UTC, zg-devj commented on main-service/src/main/java/ru/practicum/mainservice/location/LocationServiceImpl.java
> +    private LocationDto getLocationDto(NewLocationDto newLocationDto, LocationStatus status, User owner) {
Исправил, выше написал.

2023-07-20 14:53 UTC, zg-devj commented
Я так понимаю, это последнее ревью... Хотел сказать спасибо за отличные замечания и понятные комментарии к коду. Я про все проекты. Спасибо!

2023-07-21 09:21 UTC, TomattmanYandex approved these changes
Принято

2023-07-21 09:35 UTC, merged